# Generated by Django 5.0.6 on 2025-05-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediareport',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.analysisresult'),
        ),
        migrations.DeleteModel(
            name='MediaUpload',
        ),
    ]
